[project]
name = "scviewer"
version = "0.1.0"
requires-python = ">=3.12"
dependencies=[
    "pandas>=3.0,<4",
    "numpy>=2,<3",
    "dash>=4,<5",
    "scanpy[leiden]>=1.11.0"
]
readme = "README.md"
authors = [
    {name = "John T. Hardin", email = "johnhardin2021@gmail.com"}
]
description = "An easy-to-use platform for viral scRNA-seq analysis, built for wet-lab users"

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "mypy>=1.0",
    "ruff"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
scviewer="viral_platform.main:main"

[tool.pytest.ini_options]
testpaths=["tests"]
addopts = ["-q"]

[tool.mypy]
python_version="3.13"
disallow_untyped_defs=true
warn_return_any=true
warn_unused_configs=true
exclude=[
    "tests/",
    "venv/",
]