from dash import html, dcc
import dash_bootstrap_components as dbc


def create_overview_panel():
    return html.Div(
        style={
            "backgroundColor": "#eff7ff",
            "padding": "20px",
            "borderRadius": "5px",
            "border": "1px solid #000000",
            "margin": "0 0 20px 0",
        },
        className="module-panel",
        children=[
            html.H2("Overview"),
            html.H3("Navigation"),
            html.P("Use the left navigation menu to move between upload and analysis modules."),
            html.P("Each module is routed as its own Dash page."),
            html.H3("Analysis Modules"),
            html.H4("1. Upload Data"),
            html.P("Upload your single-cell RNA-seq data in .h5ad, or 10x Genomics Cell Ranger output format (.zip)."),
            html.H4("2. Quality Control"),
            html.P("After clicking 'generate QC plots', violin plots will be generated for each QC metric"),
            html.P("Use the sliders below each plot to set the upper and lower thresholds for filtering cells, then click 'Apply QC Filters'"),
            html.H4("3. Preprocessing and Clustering"),
            html.P("Click 'Run Preprocessing' to perform normalization, scaling, and PCA on the filtered dataset with default values. You can also adjust the parameters by clicking the 'Advanced Options' button."),
            html.P("After preprocessing, an elbow plot will be generated to help you choose the number of principal components (PCs) to use for clustering. Use the slider below the plot to select the number of PCs, then click 'Run Clustering' to perform clustering and generate a UMAP plot."),
            html.H4("4. Cell Annotation"),
            html.P("Click 'Run Cell Annotation' to annotate cell types using CellTypist using majority voting. This step is optional if a cell type column already exists in the dataset."),
            html.P("If used, it should be taken into consideration that identified cell types may not be completely accurate, and should be validated with known marker genes outside SCJoseki."),
            html.H4("5. Differential Expression"),
            html.P("The module presents you with 5 dropdowns. From left to right;"),
            html.Ul([
                html.Li("A grouping column to use for differential expression analysis (e.g., condition, infection status, etc.)"),
                html.Li("Based on the grouping column, choose the first group to use for comparison"),
                html.Li("Based on the grouping column, choose the second group to use for comparison"),
                html.Li("This dropdown is for selecting a cell type column to use to populate the cell type dropdown. If no cell type column exists, go back and use the cell annotation module to generate one for immediate analysis, or determine cell types outside of SCJoseki and upload a new dataset with a cell type column."),
                html.Li("Either choose a specific cell type to perform differential expression analysis on, or choose 'All Cells' to perform differential expression analysis on all cells in the dataset."),
            ]),
            html.P("After selecting the appropriate options, and changing any of the options in the Advanced Options, click 'Run Differential Expression' to perform the analysis."),
            html.H4("6. Pathway Enrichment"),
            html.P("This step can only be performed after differential expression analysis has been completed."),
            html.P("The module presents you with 3 dropdowns. From left to right;"),
            html.Ul([
                html.Li("A dropdown with the cells that successfully completed differential expression analysis. Choose the cell type you want to perform pathway enrichment analysis on."),
                html.Li("A dropdown of analysis methods, either ORA (Over Representation Analysis) or GSEA (Gene Set Enrichment Analysis)."),
                html.Li("A dropdown of pathway databases to use for enrichment analysis. (currently on GO is supported)"),
            ]),
            html.P("After selecting the appropriate options, and changing any of the options in the Advanced Options, click 'Run Pathway Enrichment' to perform the analysis."),
            html.H4("7. Viral Detection"),
            html.P("This module detects viral transcripts in the dataset based on curated viral gene sets."),
            html.P("You can choose either automatic detection or custom"),
            html.P("With automatic detection, you can choose in the dropdown to either search through all viral gene sets, or choose a specific virus to search for in the dataset."),
            html.P("With custom detection, you can input a list of viral genes to search for in the dataset. The input should be a comma-separated list of gene names (case-sensitive)."),
            html.P("After selecting the appropriate options, click 'Run Viral Detection' to perform the analysis."),
            html.H4("8. Viral Burden Analysis"),
            html.P("This module performs viral burden analysis on the dataset based on the viral detection results."),
            html.P("After configuring the advanced options, click 'Run Viral Burden Analysis' to perform the analysis."),
            html.P("The results will be displayed between multiple tabs, including a summary table, UMAP of viral infection, UMAP of viral burden, and a violin plot of viral burden across cell types and condition."),
            html.H5("8.1 Viral Burden Association Analysis"),
            html.P("Identifies variables associated with the magnitude of cellular viral burden."),
            html.H4("9. ISG Analysis"),
            html.P("Similar in structure to the viral detection module, this module detects ISG transcripts in the dataset based on curated ISG gene sets."),
            html.P("Instructions the same as for viral detection"),
            html.H4("10. Host-Virus Interaction Analysis"),
            html.P("This module identifies host genes associated with viral burden in the dataset."),
            html.P("This module can only be run after viral detection, as the dropdown is populated with the viral detection results."),
            html.P("After configuring the advanced options, click 'Run Host-Virus Interaction Analysis' to perform the analysis."),
            html.H5("10.1 Host-Virus Interaction Interpretation"),
            html.P("This module provides interpretation of the host-virus interaction results based on the IntAct database."),
            html.P("After selecting the virus and gene source, click 'Run Host-Virus Interaction Interpretation' to perform the analysis."),
            html.H4("11. Cell-Cell Communication"),
            html.P("This module identifies cell-cell communication networks in the dataset using LIANA+"),
            html.P("After configuring the advanced options, and selecting the cell type column in the first dropdown, click 'Run Cell-Cell Communication Analysis' to perform the analysis."),
            html.P("The results will be displayed between multiple tabs, including a summary table, a bubble plot, and a network plot."),
            html.P("The results can be filtered using the control at the bottom of the module."),
            html.H4("12. scMOVIR"),
            html.P("This module allows you to browse the scMOVIR database for curated viral datasets to use for comparison"),
            html.P("After selecting a dataset, use the check boxes to select the files you wish to download, then click 'Download Selected Files' to download the files."),
            html.P("The downloaded files can be used in comparison tabs for their respective modules (currently on differential expression and cell-cell communication)."),
            html.P("To remove downloaded files, use the download manager located at the bottom of the module"),
            html.H4("13. Export Data"),
            html.P("To export results, click the export button in the top right corner of the header. This will export a zip file containing a metadata CSV, a log file, and all currently generated figures/tables. The modified H5AD file will also be separately exported to either a location of your choosing, or the mounted exports directory if running in Docker."),

            
        ],
    )
